
import React, { useState, useEffect } from 'react';
import { KeyIcon } from './icons/KeyIcon';
import { CopyIcon } from './icons/CopyIcon';
import { CheckIcon } from './icons/CheckIcon';

interface PrivateKeyCardProps {
  privateKey: string;
  onGenerate: () => void;
}

export const PrivateKeyCard: React.FC<PrivateKeyCardProps> = ({ privateKey, onGenerate }) => {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!privateKey) {
        onGenerate();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleCopy = () => {
    if (!privateKey) return;
    navigator.clipboard.writeText(privateKey);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-6 md:p-8 shadow-2xl shadow-slate-900/50 h-full flex flex-col">
      <div className="flex items-center gap-4 mb-4">
        <div className="bg-amber-500/10 p-3 rounded-full border border-amber-500/20">
          <KeyIcon className="w-6 h-6 text-amber-400" />
        </div>
        <h2 className="text-2xl md:text-3xl font-bold text-slate-100">The Private Key</h2>
      </div>
      <p className="text-slate-400 mb-6 flex-grow">
        This is your ultimate secret. A private key is a massive 256-bit number that acts as the password to your Bitcoin. Anyone who knows this key can spend your funds. It's the "remote control" for your digital assets.
      </p>

      <div className="bg-slate-900 rounded-lg p-4 mb-4 min-h-[110px] flex flex-col justify-center">
        <label className="text-xs text-slate-500 mb-1">Your Generated 32-Byte (256-bit) Key:</label>
        <div className="flex items-center gap-2">
            <p className="text-amber-300 font-mono break-all text-sm md:text-base flex-1">
                {privateKey || 'Click generate to create a new key.'}
            </p>
            {privateKey && (
                <button
                    onClick={handleCopy}
                    className="p-2 rounded-md hover:bg-slate-700 transition-colors text-slate-400"
                    aria-label="Copy private key"
                >
                    {copied ? <CheckIcon className="w-5 h-5 text-green-400" /> : <CopyIcon className="w-5 h-5" />}
                </button>
            )}
        </div>
      </div>
      
      <div className="bg-red-900/50 border border-red-700 text-red-300 text-sm rounded-lg p-3 text-center mb-6">
        <strong>Warning:</strong> This is for educational purposes ONLY. Never use a key generated by a website for real funds.
      </div>
      
      <button
        onClick={onGenerate}
        className="w-full bg-amber-500 text-slate-900 font-bold py-3 px-6 rounded-lg hover:bg-amber-400 transition-all duration-300 transform hover:scale-105 shadow-lg shadow-amber-900/50"
      >
        Generate New Private Key
      </button>
    </div>
  );
};
